export type Category = "arroces" | "tallarines" | "wok" | "menu" | "combos" | "sopas" | "bebidas"

export type Dish = {
  id: string
  name: string
  description: string
  price: number
  image: string
  category: Category
  badge?: string
  rating: number
  popular?: boolean
}

export const CATEGORIES: { value: Category | "todos"; label: string }[] = [
  { value: "todos", label: "Todos" },
  { value: "arroces", label: "Arroces" },
  { value: "tallarines", label: "Tallarines" },
  { value: "wok", label: "Platos al Wok" },
  { value: "menu", label: "Menu" },
  { value: "combos", label: "Combos" },
  { value: "sopas", label: "Sopas" },
  { value: "bebidas", label: "Bebidas" },
]

export const MENU: Dish[] = [
  // Arroces - Carta
  {
    id: "arroz-chaufa",
    name: "Arroz Chaufa",
    description: "",
    price: 20.0,
    image:
      "/dishes/ChaufaCarta.jpg",
    category: "arroces",
    badge: "Tradicional",
    rating: 4.9,
    popular: true,
  },
  {
    id: "arroz-chaufa-especial",
    name: "Arroz Chaufa Especial",
    description: "",
    price: 23.0,
    image:
      "/dishes/ChaufaEspecial.jpg",
    category: "arroces",
    rating: 4.7,
  },
  {
    id: "arroz-chaufa-carne",
    name: "Arroz Chaufa de Carne",
    description: "",
    price: 25.0,
    image: "/dishes/ArrozChaufaCarne.jpg",
    category: "arroces",
    badge: "Premium",
    rating: 4.8,
  },
    {
    id: "areopuerto-pollo",
    name: "Aeropuerto de Pollo",
    description: "",
    price: 21.0,
    image: "/dishes/AeropuertoPollo.jpg",
    category: "arroces",
    badge: "Premium",
    rating: 4.5,
  },
    {
    id: "areopuerto-carne",
    name: "Aeropuerto con Carne",
    description: "",
    price: 23.0,
    image: "/dishes/AeropuertoCarne.jpg",
    category: "arroces",
    badge: "Premium",
    rating: 4.7,
  },
    {
    id: "combinado-pollo",
    name: "Combinado de Pollo",
    description: "",
    price: 24.0,
    image: "/dishes/CombinadoPollo.jpg",
    category: "arroces",
    badge: "Tradicional",
    rating: 4.5,
  },

  // Tallarines - Carta
  {
    id: "tallarin-pollo-trozos",
    name: "Tallarín con Pollo en Trozos",
    description: "",
    price: 23.0,
    image: "/dishes/TallarinPollo.jpg",
    category: "tallarines",
    badge: "Clásico",
    rating: 4.9,
    popular: true,
  },
  {
    id: "tallarin-carne",
    name: "Tallarín con Carne",
    description: "",
    price: 24.0,
    image: "/dishes/TallarinCarne.png",
    category: "tallarines",
    rating: 4.6,
  },
  {
    id: "pollo-champinones",
    name: "Pollo en Trozos con Champiñones",
    description: "",
    price: 24.0,
    image: "/dishes/PolloChampinones.png",
    category: "tallarines",
    badge: "De la Casa",
    rating: 4.8,
  },
  {
    id: "pollo-verduras",
    name: "Pollo en Trozos con Verduras",
    description: "",
    price: 23.5,
    image: "/dishes/PolloVerduras.jpg",
    category: "tallarines",
    rating: 4.7,
  },

  // Platos al Wok - Carta
  {
    id: "kam-lu-wantan",
    name: "Kam Lu Wantán",
    description: "",
    price: 24.5,
    image:
      "/dishes/KanluWantan.jpg",
    category: "wok",
    badge: "Favorito",
    rating: 5.0,
    popular: true,
  },
  {
    id: "pollo-tipakay",
    name: "Pollo Tipakay",
    description: "",
    price: 22.5,
    image: "/dishes/PolloTipakay.jpg",
    category: "wok",
    rating: 4.7,
  },
  {
    id: "chijaukay",
    name: "Pollo Chijaukay",
    description: "",
    price: 22.5,
    image: "/dishes/ChijaukayPollo.jpg",
    category: "wok",
    badge: "Más Pedido",
    rating: 4.8,
    popular: true,
  },
  {
    id: "limonkay",
    name: "Limonkay con Pollo",
    description: "",
    price: 23.0,
    image: "/dishes/Limonkay.jpg",
    category: "wok",
    badge: "Más Pedido",
    rating: 4.9,
    popular: true,
  },
  {
    id: "pollo-tausi",
    name: "Pollo en Trozo con Tausi",
    description: "",
    price: 23.0,
    image: "/dishes/PolloTausi.jpg",
    category: "wok",
    rating: 4.7,
    popular: true,
  },
  {
    id: "pollo-tamarindo",
    name: "Pollo con Tamarindo",
    description: "",
    price: 23.0,
    image: "/dishes/PolloTamarindo.jpg",
    category: "wok",
    badge: "Más Pedido",
    rating: 4.4,
    popular: true,
  },
    {
    id: "pollo-frejolito",
    name: "Pollo Trozos con Frejolito",
    description: "",
    price: 24.0,
    image: "/dishes/PolloFrijolito.jpg",
    category: "wok",
    rating: 4.7,
    popular: true,
  },
    {
    id: "carne-frejolito",
    name: "Carne de Res con Frejolito",
    description: "",
    price: 26.0,
    image: "/dishes/CarneFrejolito.png",
    category: "wok",
    rating: 4.3,
    popular: true,
  },

  // Platos Menu
  {
    id: "chaufa-pollo-menu",
    name: "Chaufa de Pollo",
    description: "",
    price: 14.0,
    image: "/dishes/ChaufaPollo.jpg",
    category: "menu",
    rating: 4.8,
  },
  {
    id: "chaufa-res-menu",
    name: "Chaufa con Carne Res",
    description: "",
    price: 16.5,
    image: "/dishes/ArrozChaufaCarne.jpg",
    category: "menu",
    rating: 4.6,
  },
  {
    id: "aeropuerto-menu",
    name: "Aeropuerto de Pollo",
    description: "",
    price: 15.5,
    image: "/dishes/AeropuertoPollo.jpg",
    category: "menu",
    badge: "Especial",
    rating: 4.9,
  },
    {
    id: "aeropuerto-carne-menu",
    name: "Aeropuerto de Carne",
    description: "",
    price: 17.5,
    image: "/dishes/AeropuertoCarne.jpg",
    category: "menu",
    rating: 4.5,
  },
  {
    id: "tallarin-pollo-menu",
    name: "Tallarin con Pollo",
    description: "",
    price: 15.0,
    image: "/dishes/TallarinPollo.jpg",
    category: "menu",
    rating: 4.6,
  },
  {
    id: "tallarin-carne-menu",
    name: "Tallarin con Carne",
    description: "",
    price: 16.5,
    image: "/dishes/TallarinCarne.png",
    category: "menu",
    rating: 4.6,
  },
    {
    id: "combinado-pollo-menu",
    name: "Combinado de Pollo",
    description: "",
    price: 16.5,
    image: "/dishes/CombinadoPollo.jpg",
    category: "menu",
    rating: 4.7,
  },
  {
    id: "combinado-chancho-menu",
    name: "Combinado de Chancho",
    description: "",
    price: 17.5,
    image: "/dishes/CombinadoChancho.jpg",
    category: "menu",
    rating: 4.6,
  },
  {
    id: "pollo-tausi-menu",
    name: "Pollo con Tausi",
    description: "",
    price: 18.0,
    image: "/dishes/PolloTausi.jpg",
    category: "menu",
    badge: "Especial",
    rating: 4.9,
  },
    {
    id: "chijaukay-menu",
    name: "Chijaukay con Pollo",
    description: "",
    price: 18.0,
    image: "/dishes/ChijaukayPollo.jpg",
    category: "menu",
    rating: 4.5,
  },
    {
    id: "enrollado-pollo-menu",
    name: "Enrollado con Pollo",
    description: "",
    price: 19.0,
    image: "/dishes/EnrolladoPollo.jpg",
    category: "menu",
    badge: "Especial",
    rating: 4.7,
  },
    {
    id: "limonkay-menu",
    name: "Limonkay con Pollo",
    description: "",
    price: 19.0,
    image: "/dishes/Limonkay.jpg",
    category: "menu",
    rating: 4.5,
  },
    {
    id: "tortilla-pollo-menu",
    name: "Tortilla con Pollo",
    description: "",
    price: 17.5,
    image: "/dishes/TortillaPollo.jpg",
    category: "menu",
    badge: "Especial",
    rating: 4.9,
  },
    {
    id: "tortilla-chancho-menu",
    name: "Tortilla con Chancho",
    description: "",
    price: 19.0,
    image: "/dishes/TortillaChancho.jpg",
    category: "menu",
    rating: 4.4,
  },

    // Combos
  {
    id: "chijaukay-combo",
    name: "Pollo Chijaukay+Enrollado",
    description: "",
    price: 25.0,
    image: "/dishes/ChijaukayCombo.jpg",
    category: "combos",
    rating: 4.7,
  },
  {
    id: "tipakay-combo",
    name: "Pollo Chijaukay+Tikapay",
    description: "",
    price: 25.0,
    image: "/dishes/TipakayCombo.png",
    category: "combos",
    rating: 4.9,
  },
    {
    id: "enrollado-combo",
    name: "Pollo Tikapay+Enrollado",
    description: "",
    price: 25.0,
    image: "/dishes/EnrolladoCombo.png",
    category: "combos",
    rating: 4.8,
  },
  {
    id: "verdura-combo",
    name: "Pollo con Verdura+Enrollado",
    description: "",
    price: 25.0,
    image: "/dishes/VerdurasCombo.jpg",
    category: "combos",
    rating: 4.5,
  },

    // Sopas
  {
    id: "sopa-wantan",
    name: "Sopa Wantán",
    description: "",
    price: 14.0,
    image: "/dishes/SopaWantan.jpg",
    category: "sopas",
    rating: 4.8,
  },
  {
    id: "sopa-womin",
    name: "Sopa Womin Especial",
    description: "",
    price: 18.0,
    image: "/dishes/SopaWomin.jpg",
    category: "sopas",
    rating: 4.6,
  },
  {
    id: "sopa-pacpow",
    name: "Sopa Pac Pow Especial",
    description: "",
    price: 19.0,
    image: "/dishes/SopaPacPow.jpg",
    category: "sopas",
    badge: "Especial",
    rating: 4.3,
  },
  {
    id: "wantanes-frito",
    name: "Wantanes Frito",
    description: "1/2 Docena",
    price: 10.0,
    image: "/dishes/Wantanes.jpg",
    category: "sopas",
    badge: "Especial",
    rating: 4.9,
  },

      // Bebidas
  {
    id: "gaseosa-personal",
    name: "Inka Kola Personal",
    description: "",
    price: 3.0,
    image: "/dishes/Inka Kola Personal.jpg",
    category: "bebidas",
    rating: 4.8,
  },
  {
    id: "gaseosa-litro",
    name: "Inka Kola 1 1/2",
    description: "",
    price: 9.0,
    image: "/dishes/InkaKola.jpg",
    category: "bebidas",
    rating: 4.4,
  },

]

export function formatPrice(value: number) {
  return `S/. ${value.toFixed(2)}`
}

export function getDishById(id: string) {
  return MENU.find((d) => d.id === id)
}
